# Autogenerated file.
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#  @generated
 
class ProtocAT321 < Formula
  desc "Protocol buffers (Google's data interchange format)"
  homepage "https://github.com/protocolbuffers/protobuf/"
  version "3.2.1"
  url "https://github.com/protocolbuffers/protobuf/archive/v3.2.1.zip"
  license "BSD-3-Clause"

  depends_on "cmake" => :build
  depends_on "ninja" => :build
  depends_on "gcc" => :build

  keg_only :versioned_formula

  def install
    # skip rpath
    inreplace "cmake/install.cmake", "if (UNIX AND NOT APPLE)", "if (OFF)", false

    mkdir "build" do
      args = std_cmake_args + %W[
        -GNinja
        --log-level=STATUS
        -DCMAKE_C_COMPILER=#{Formula["gcc"].opt_bin}/gcc-10
        -DCMAKE_CXX_COMPILER=#{Formula["gcc"].opt_bin}/g++-10
        -DCMAKE_BUILD_TYPE=MinSizeRel
        -DBUILD_SHARED_LIBS=OFF
        -Dprotobuf_WITH_ZLIB=OFF
        -Dprotobuf_BUILD_TESTS=OFF
      ]
      # -DCMAKE_FIND_LIBRARY_SUFFIXES='.a'
      args << "-DCMAKE_CXX_FLAGS_MINSIZEREL='-Os -DNDEBUG -s'"
      args << "-DCMAKE_EXE_LINKER_FLAGS='-static'" if OS.linux?
      # args << "-DCMAKE_EXE_LINKER_FLAGS='-static-libgcc -static-libstdc++'" if OS.mac?

      system "cmake", *args, "../cmake"
      system "ninja"
      system "ninja install"

      bin.install "protoc"
    end
  end

  test do
    output = shell_output("ldd #{bin}/protoc 2>&1", 1).strip
    assert_equal "not a dynamic executable", output

    output = shell_output("#{bin}/protoc --version")
    assert_equal "libprotoc 3.2.0", output.strip
  end
end