name: build protoc
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-protoc.yaml'
      - 'Formula/protoc.rb'
      - 'action/install/action.yaml'
  release:
    types: [created]

jobs:
  install:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        version:
          - '3.1.0'
          - '3.2.0'
          - '3.3.2'
          - '3.4.1'
          - '3.5.2'
          - '3.7.1'
          - '3.8.0'
          - '3.9.2'
          - '3.13.0.1'
          - '3.14.0'
          - '3.15.6'
          - '3.16.0'
          - '3.17.3'
          - '3.18.2'
          - '3.19.4'
          - '3.20.0'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install binary
        uses: ./action/install
        with:
          formula: protoc
          env: 'HOMEBREW_PROTOC_VERSION=${{ matrix.version }}'

      - name: check binary
        run: |
          ls -lah bin
          mkdir -p dist/bin
          mv bin dist/bin/${{ matrix.version }}

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries-${{ matrix.version }}
          path: dist
          retention-days: 1

  upload-release:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip3 install typer
      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.1.0

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.2.0

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.3.2

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.4.1

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.5.2

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.7.1

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.8.0

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.9.2

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.13.0.1

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.14.0

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.15.6

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.16.0

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.17.3

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.18.2

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.19.4

      - uses: actions/download-artifact@v2
        with:
          name: binaries-3.20.0

      - name: list files
        run: ls -lahR bin

      - name: prepare files
        run: ./pack.py bin dist protoc

      - name: upload binaries to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          overwrite: true
          file_glob: true
          tag: ${{ github.ref }}
          prerelease: true
