name: build xz
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-xz.yaml'
      - 'Formula/xz.rb'
      - 'action/install/action.yaml'

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        version:
          - '5.2.5'
          - '5.0.8'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install binary
        uses: ./action/install
        with:
          formula: xz
          env: 'HOMEBREW_XZ_VERSION=${{ matrix.version }}'

      - name: check binary
        run: ls -lah bin
