name: build llvm static
on:
  push:

jobs:
  install:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        os: [macos-latest, ubuntu-20.04]
        version: [3, 4, 5, 6, 7, 8, 9, 10, 11]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v2

      - name: uninstall some pre installed packages
        run: sudo apt purge -y libz3-4 libz3-dev || echo "skip"

      - uses: curoky/actions/brew-tap-install-test@master
        with:
          formula: llvm-static@${{ matrix.version }}

      - name: get llvm install path
        id: get_brew_llvm_path
        run: echo ::set-env name=BREW_LLVM_PATH::$(brew --prefix llvm-static@${{ matrix.version }})

      - uses: actions/upload-artifact@v2
        with:
          name: llvm-@${{ matrix.version }}-${{ matrix.os }}
          path: ${{ env.BREW_LLVM_PATH}}/bin
