name: build llvm tools
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-llvm-tools.yaml'
      - 'Formula/llvm-tools.rb'
      - 'action/install/action.yaml'
  release:
    types: [created]

jobs:
  install:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        version:
          - '3.9.1'
          - '4.0.1'
          - '5.0.2'
          - '6.0.1'
          - '7.1.0'
          - '8.0.1'
          - '9.0.1'
          - '10.0.1'
          - '11.0.0'
          - '12.0.1'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # FIXME(curoky): remove follow trick
      - name: remove libtinfo
        run: |
          brew install ncurses && brew unlink ncurses
          sudo rm -rf /usr/lib/x86_64-linux-gnu/libtinfo.so

      - name: install binary
        uses: ./action/install
        with:
          formula: llvm-tools
          env: 'HOMEBREW_LLVMTOOLS_VERSION=${{ matrix.version }}'

      - name: check binary
        run: ls -lah bin

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries-${{ matrix.version }}
          path: bin
          retention-days: 1

  upload-release:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: binaries-10.0.1
          path: bin/10.0.1

      - uses: actions/download-artifact@v2
        with:
          name: binaries-11.0.0
          path: bin/11.0.0

      - uses: actions/download-artifact@v2
        with:
          name: binaries-12.0.1
          path: bin/12.0.1

      - name: list files
        run: ls -lahR bin

      - name: prepare files
        run: |
          mkdir dist
          mv bin/10.0.1/clang-format dist/clang-format-10.0.1
          mv bin/11.0.0/clang-format dist/clang-format-11.0.0
          mv bin/12.0.1/clang-format dist/clang-format-12.0.1
          mv bin/10.0.1/clang-query dist/clang-query-10.0.1
          mv bin/11.0.0/clang-query dist/clang-query-11.0.0
          mv bin/12.0.1/clang-query dist/clang-query-12.0.1
          mv bin/10.0.1/clang-tidy dist/clang-tidy-10.0.1
          mv bin/11.0.0/clang-tidy dist/clang-tidy-11.0.0
          mv bin/12.0.1/clang-tidy dist/clang-tidy-12.0.1

      - name: upload binaries to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          overwrite: true
          file_glob: true
          tag: ${{ github.ref }}
          prerelease: true
