name: build tmux
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-tmux.yaml'
      - 'Formula/tmux.rb'
      - 'src/action/install.yaml'

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        version:
          - '3.2a'
          - '2.9a'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install binary
        uses: ./action/install
        with:
          formula: tmux
          env: 'HOMEBREW_TMUX_VERSION=${{ matrix.version }}'

      - name: check binary
        run: ls -la /home/linuxbrew/.linuxbrew/opt/tmux/bin/tmux
