name: build xz
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-xz.yaml'
      - 'Formula/xz.rb'
      - 'action/install/action.yaml'

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        version:
          - '5.2.5'
          - '5.0.8'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install binary
        uses: ./action/install
        with:
          formula: xz
          env: 'HOMEBREW_XZ_VERSION=${{ matrix.version }}'

      - name: check binary
        run: ls -lah bin

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.version }}-binaries
          path: bin
          retention-days: 1

  upload-release:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: 5.2.5-binaries

      - uses: actions/download-artifact@v2
        with:
          name: 5.0.8-binaries

      - name: list files
        run: ls -laR . && ls bin

      - uses: mxschmitt/action-tmate@v3
        if: true
        timeout-minutes: 30
