name: build llvm static
on:
  push:

jobs:
  install:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        os: [macos-latest, ubuntu-20.04]
        version: [3, 4, 5, 6, 7, 8, 9, 10, 11]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v2

      - name: Install some tools
        run: brew install openssl@1.1

      - name: Uninstall some pre installed packages
        run: sudo apt purge -y libz3-4 libz3-dev || echo "skip"

      - name: Build llvm static binary
        uses: curoky/actions/brew-tap-install-test@master
        with:
          formula: llvm-static@${{ matrix.version }}

      - name: Set target env
        id: set_target_env
        run: |
          echo "TARGET_PATH=$(brew --prefix llvm-static@${{ matrix.version }})/bin" >> $GITHUB_ENV
          echo "TARGET_VERSION=${{ matrix.version }}-$(uname)-$(uname -m)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: llvm-${{ matrix.version }}-${{ matrix.os }}
          path: ${{ env.TARGET_PATH }}

      - name: Prepare binaries
        run: |
          find ${{ env.TARGET_PATH }} -type f -exec bash -c 'mv $0 $0-${{ env.TARGET_VERSION }}' {} \;
          find ${{ env.TARGET_PATH }} -type f -exec bash -c 'openssl sha256 -r -out $0.sha256 $0' {} \;

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.TARGET_PATH }}/**
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
