name: build linux v2

on:
  # push:
  #   branches:
  #     - master
  #     - dev
  push:
    paths:
      - '.github/workflows/build-linux-v2.yaml'
      - 'pkgs/**'
      - 'pkgs-list/**'
      - 'scripts/**'
      - 'flake*'
  workflow_dispatch:
    inputs:
      name:
        description: 'package name'
        default: ''
        required: false
        type: string
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        include:
          - name: aria2
          - name: atuin
          - name: autoconf
          - name: automake
          - name: bash
          - name: bat
          - name: bazelisk
          - name: binutils
          # - name: biome
          - name: bison
          - name: buildifier
          - name: bzip2
          - name: cacert
          - name: cloc
          - name: cmake
          - name: connect
          - name: coreutils
          - name: croc
          - name: cronie
          - name: curl
          - name: diffutils
          - name: dive
          - name: dool
          - name: dprint
          - name: ethtool
          - name: exiftool
          - name: eza
          - name: fd
          - name: file
          - name: findutils
          - name: flac
          - name: flex
          - name: fzf
          - name: gawk
          - name: gdb
          - name: gdu
          - name: getopt
          - name: gettext
          - name: gh
          - name: git
          - name: git-absorb
          - name: git-extras
          - name: git-filter-repo
          - name: git-lfs
          - name: glibcLocales
          - name: gnugrep
          - name: gnumake
          - name: gnupatch
          - name: gnupg
          - name: gnused
          - name: gnutar
          - name: go-task
          - name: gost
          - name: gzip
          - name: indent
          - name: inetutils
          - name: iproute2
          - name: iptables
          - name: iputils
          - name: jq
          - name: krb5
          - name: lefthook
          - name: less
          - name: libcap
          - name: libtool
          - name: lsb-release
          - name: lsof
          - name: lua
          - name: m4
          - name: makeself
          # - name: man
          - name: mcfly
          - name: miniserve
          - name: music-decrypto
          - name: ncdu_1
          - name: netcat
          - name: netron
          - name: nettools
          - name: ninja
          - name: nixfmt
          # - name: nsight-systems
          - name: numactl
          - name: openssh_gssapi
          - name: openssl
          - name: oras
          - name: p7zip
          - name: parallel
          - name: patchelf
          - name: perl
          - name: pkg-config
          - name: procps
          - name: procs
          - name: protobuf_23
          - name: protobuf_24
          - name: protobuf_25
          - name: protobuf_26
          - name: protobuf_27
          - name: protobuf_28
          - name: protobuf_29
          - name: protobuf_3_8_0
          - name: protobuf_3_9_2
          - name: protobuf3_20
          - name: protobuf3_21
          - name: python311
          - name: python312
          - name: python313
          - name: rime-plugs
          - name: ripgrep
          - name: rsync
          - name: ruff
          - name: scc
          - name: shellcheck
          - name: shfmt
          # - name: silver-searcher
          - name: snappy
          - name: sqlite
          - name: starship
          - name: strace
          - name: tmux
          - name: tmux-plugs
          - name: tree
          - name: tzdata
          - name: unzip
          - name: util-linux
          - name: uv
          - name: vim
          - name: vim-plugs
          - name: wget
          - name: xxd
          - name: xz
          - name: yazi
          - name: zellij
          - name: zip
          - name: zlib
          - name: zlib-ng
          - name: zsh
          - name: zsh-plugs
          - name: zstd

          - name: s6
          - name: s6-rc
          - name: s6-linux-init
          - name: s6-linux-utils
          - name: s6-portable-utils
          - name: s6-networking
          - name: s6-dns
          - name: skalibs
          - name: execline

          - name: lxgw-wenkai
          - name: fira-code
          - name: nerd-fonts.fira-code
          - name: nerd-fonts.ubuntu-mono

    steps:
      - run: echo "skip_steps=true" >> $GITHUB_ENV
      - run: echo "skip_steps=false" >> $GITHUB_ENV
        if: ${{ (github.event_name == 'workflow_dispatch' && (inputs.name == matrix.name || inputs.name == '*')) || (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'schedule' }}

      - uses: actions/checkout@v5
        if: ${{ env.skip_steps != 'true' }}

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y rsync
        if: ${{ env.skip_steps != 'true' }}

      - uses: DeterminateSystems/nix-installer-action@main
        if: ${{ env.skip_steps != 'true' }}

      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix config show substituters
        if: ${{ env.skip_steps != 'true' }}

      - uses: cachix/cachix-action@v15
        with:
          name: curoky-static-binaries-v2
          authToken: 'eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzOGM0YzAxOC0xY2I1LTRiZGUtOWVhMy03YzFmZDk2Mjc4ZDAiLCJzY29wZXMiOiJjYWNoZSJ9.VrYQP0zavhmHR3k1qNFbRUB3jP_jiJysOZrGJrvwA2M'
        if: ${{ env.skip_steps != 'true' }}
      - run: |
          nix build .#${{ matrix.name }}
          nix-store -qR $(readlink -f ./result)
          nix-store -qR $(readlink -f ./result) | cachix push curoky-static-binaries-v2
          rsync -av --copy-unsafe-links ./result/ ./${{ matrix.name }}/
          tar -czvf ./${{ matrix.name }}.linux-x86_64.tar.gz ./${{ matrix.name }}
        if: ${{ env.skip_steps != 'true' }}

      - uses: oras-project/setup-oras@v1
        if: ${{ env.skip_steps != 'true' }}

      # - uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin
        if: ${{ env.skip_steps != 'true' }}

      - run: >
          oras push ghcr.io/curoky/static-binaries-v3:${{ matrix.name }}-linux-x86_64
          ./${{ matrix.name }}.linux-x86_64.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip
        if: ${{ env.skip_steps != 'true' }}
