name: test on linux
on:
  schedule:
    - cron: '0 16 * * *'
  push:

jobs:
  install:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        os: [ubuntu16.04, ubuntu18.04, ubuntu20.04]
        package:
          - thrift@0.9.3

    runs-on: ubuntu-latest

    container:
      image: homebrew/${{ matrix.os }}

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v2

      - name: setup tap
        run: brew tap curoky/curoky

      - uses: curoky/actions/brew-tap-install-test@master
        with:
          formula: ${{ matrix.package }}
